# ======================================
#    Mining Configuration
# ======================================
# mining_enabled: False
# mining_address: ''
# mining_thread_count: 0  # 0 to auto detect thread count based on CPU/GPU number of processors
#
# ======================================
#    Ephemeral Configuration
# ======================================
# accept_ephemeral: True
# outgoing_message_expiry: 90
# Cache Size
# lru_state_cache_size: 10
# max_state_limit: 10

# ======================================
#    P2P Configuration
# ======================================
# enable_peer_discovery: True  # Allows to discover new peers from the connected peers
# p2p_local_port: 19000
# p2p_public_port: 19000
# peer_rate_limit: 500  # Max Number of messages per minute per peer
# ban_minutes: 20              # Allows to ban a peer's IP who is breaking protocol
# monitor_connections_interval: 30
# max_peers_limit: 100  # Number of allowed peers
# chain_state_timeout: 180
# chain_state_broadcast_period: 30              # must be less than ping_timeout
# transaction_pool_size: 25000
# pending_transaction_pool_size: 75000
# stale_transaction_threshold: 15               # 15 Blocks
#
# peer_list:
#  - 35.178.79.137
#  - 35.177.182.85
#  - 18.130.119.29
#  - 18.130.25.64
#
# ntp_servers:
#   - pool.ntp.org
#   - ntp.ubuntu.com
#
# ======================================
#        ADMIN API CONFIGURATION
# ======================================
# admin_api_enabled: False
# admin_api_host: "127.0.0.1"
# admin_api_port: 19008
# admin_api_threads: 1
# admin_api_max_concurrent_rpc: 100
#
# ======================================
#        PUBLIC API CONFIGURATION
# ======================================
# public_api_enabled: True
# public_api_host: "0.0.0.0"
# public_api_port: 19009
# public_api_threads: 1
# public_api_max_concurrent_rpc: 100
#
# ======================================
#        MINING API CONFIGURATION
# ======================================
# mining_api_enabled: False
# mining_api_host: "127.0.0.1"
# mining_api_port: 19007
# mining_api_threads: 1
# mining_api_max_concurrent_rpc: 100
#
# ======================================
#        GRPC PROXY CONFIGURATION
# ======================================
# grpc_proxy_host: "127.0.0.1"
# grpc_proxy_port: 18090
# p2p_q_size: 1000
# outgoing_message_expiry: 90  # Outgoing message expires after 90 seconds
#
# ======================================
#      WALLET DAEMON CONFIGURATION
# ======================================
# public_api_server = "127.0.0.1:19009"
# wallet_daemon_host = "127.0.0.1"
# wallet_daemon_port = 18091
#
# ======================================
#        WALLET API CONFIGURATION
# ======================================
# wallet_api_host = "127.0.0.1"
# wallet_api_port = 19010
# wallet_api_threads = 1
# wallet_api_max_concurrent_rpc = 100


